### ISSUE TITLE
Uso de mayúsculas en los RestControllers

### ISSUE THREAD

**Issue by AndrewGlez** [ABEL0S0/GameControlEmotions#1]
https://github.com/ABEL0S0/GameControlEmotions/blob/b68f210f97e0bc57b14af924992e70e67ab3bb03/src/main/java/com/pucese/gamecontrolemotions/Controller/UsuarioController.java#L24

https://github.com/ABEL0S0/GameControlEmotions/blob/b68f210f97e0bc57b14af924992e70e67ab3bb03/src/main/java/com/pucese/gamecontrolemotions/Controller/UsuarioController.java#L55

**Comment by DevinLlerena23** [comment]
ready

**Comment by ABEL0S0** [comment]
I've already change that, so fuck you
